import { Sofa } from './sofa';

export const data: Sofa[] = [
  { name: '1',
    style: 'hi-tech',
    material: 'acrylic',
    color: 'black',
    origin: 'china',
  },
  { name: '241',
    style: 'hi-tech',
    material: 'acrylic',
    color: 'black',
    origin: 'china',
  },
  { name: '2',
    style: 'hi-tech',
    material: 'polyester',
    color: 'black',
    origin: 'china',
  },
  { name: '3',
    style: 'hi-tech',
    material: 'wool',
    color: 'black',
    origin: 'china',
  },
  { name: '4',
    style: 'hi-tech',
    material: 'leather',
    color: 'black',
    origin: 'china',
  },
  { name: '5',
    style: 'hi-tech',
    material: 'acrylic',
    color: 'brown',
    origin: 'china',
  },
  { name: '6',
    style: 'hi-tech',
    material: 'polyester',
    color: 'brown',
    origin: 'china',
  },
  { name: '7',
    style: 'hi-tech',
    material: 'wool',
    color: 'brown',
    origin: 'china',
  },
  { name: '8',
    style: 'hi-tech',
    material: 'leather',
    color: 'brown',
    origin: 'china',
  },
  { name: '9',
    style: 'hi-tech',
    material: 'acrylic',
    color: 'white',
    origin: 'china',
  },
  { name: '10',
    style: 'hi-tech',
    material: 'polyester',
    color: 'white',
    origin: 'china',
  },
  { name: '11',
    style: 'hi-tech',
    material: 'wool',
    color: 'white',
    origin: 'china',
  },
  { name: '12',
    style: 'hi-tech',
    material: 'leather',
    color: 'white',
    origin: 'china',
  },
  { name: '13',
    style: 'hi-tech',
    material: 'acrylic',
    color: 'red',
    origin: 'china',
  },
  { name: '14',
    style: 'hi-tech',
    material: 'polyester',
    color: 'red',
    origin: 'china',
  },
  { name: '15',
    style: 'hi-tech',
    material: 'wool',
    color: 'red',
    origin: 'china',
  },
  { name: '16',
    style: 'hi-tech',
    material: 'leather',
    color: 'red',
    origin: 'china',
  },

  { name: '17',
    style: 'hi-tech',
    material: 'acrylic',
    color: 'black',
    origin: 'japan',
  },
  { name: '18',
    style: 'hi-tech',
    material: 'polyester',
    color: 'black',
    origin: 'japan',
  },
  { name: '19',
    style: 'hi-tech',
    material: 'wool',
    color: 'black',
    origin: 'japan',
  },
  { name: '20',
    style: 'hi-tech',
    material: 'leather',
    color: 'black',
    origin: 'japan',
  },
  { name: '21',
    style: 'hi-tech',
    material: 'acrylic',
    color: 'brown',
    origin: 'japan',
  },
  { name: '22',
    style: 'hi-tech',
    material: 'polyester',
    color: 'brown',
    origin: 'japan',
  },
  { name: '23',
    style: 'hi-tech',
    material: 'wool',
    color: 'brown',
    origin: 'japan',
  },
  { name: '24',
    style: 'hi-tech',
    material: 'leather',
    color: 'brown',
    origin: 'japan',
  },
  { name: '25',
    style: 'hi-tech',
    material: 'acrylic',
    color: 'white',
    origin: 'japan',
  },
  { name: '26',
    style: 'hi-tech',
    material: 'polyester',
    color: 'white',
    origin: 'japan',
  },
  { name: '27',
    style: 'hi-tech',
    material: 'wool',
    color: 'white',
    origin: 'japan',
  },
  { name: '28',
    style: 'hi-tech',
    material: 'leather',
    color: 'white',
    origin: 'japan',
  },
  { name: '29',
    style: 'hi-tech',
    material: 'acrylic',
    color: 'red',
    origin: 'japan',
  },
  { name: '30',
    style: 'hi-tech',
    material: 'polyester',
    color: 'red',
    origin: 'japan',
  },
  { name: '31',
    style: 'hi-tech',
    material: 'wool',
    color: 'red',
    origin: 'japan',
  },
  { name: '32',
    style: 'hi-tech',
    material: 'leather',
    color: 'red',
    origin: 'japan',
  },

  { name: '33',
    style: 'hi-tech',
    material: 'acrylic',
    color: 'black',
    origin: 'italy',
  },
  { name: '34',
    style: 'hi-tech',
    material: 'polyester',
    color: 'black',
    origin: 'italy',
  },
  { name: '35',
    style: 'hi-tech',
    material: 'wool',
    color: 'black',
    origin: 'italy',
  },
  { name: '36',
    style: 'hi-tech',
    material: 'leather',
    color: 'black',
    origin: 'italy',
  },
  { name: '37',
    style: 'hi-tech',
    material: 'acrylic',
    color: 'brown',
    origin: 'italy',
  },
  { name: '38',
    style: 'hi-tech',
    material: 'polyester',
    color: 'brown',
    origin: 'italy',
  },
  { name: '39',
    style: 'hi-tech',
    material: 'wool',
    color: 'brown',
    origin: 'italy',
  },
  { name: '40',
    style: 'hi-tech',
    material: 'leather',
    color: 'brown',
    origin: 'italy',
  },
  { name: '41',
    style: 'hi-tech',
    material: 'acrylic',
    color: 'white',
    origin: 'italy',
  },
  { name: '42',
    style: 'hi-tech',
    material: 'polyester',
    color: 'white',
    origin: 'italy',
  },
  { name: '43',
    style: 'hi-tech',
    material: 'wool',
    color: 'white',
    origin: 'italy',
  },
  { name: '44',
    style: 'hi-tech',
    material: 'leather',
    color: 'white',
    origin: 'italy',
  },
  { name: '45',
    style: 'hi-tech',
    material: 'acrylic',
    color: 'red',
    origin: 'italy',
  },
  { name: '46',
    style: 'hi-tech',
    material: 'polyester',
    color: 'red',
    origin: 'italy',
  },
  { name: '47',
    style: 'hi-tech',
    material: 'wool',
    color: 'red',
    origin: 'italy',
  },
  { name: '48',
    style: 'hi-tech',
    material: 'leather',
    color: 'red',
    origin: 'italy',
  },

  { name: '49',
    style: 'hi-tech',
    material: 'acrylic',
    color: 'black',
    origin: 'sweden',
  },
  { name: '50',
    style: 'hi-tech',
    material: 'polyester',
    color: 'black',
    origin: 'sweden',
  },
  { name: '51',
    style: 'hi-tech',
    material: 'wool',
    color: 'black',
    origin: 'sweden',
  },
  { name: '52',
    style: 'hi-tech',
    material: 'leather',
    color: 'black',
    origin: 'sweden',
  },
  { name: '53',
    style: 'hi-tech',
    material: 'acrylic',
    color: 'brown',
    origin: 'sweden',
  },
  { name: '54',
    style: 'hi-tech',
    material: 'polyester',
    color: 'brown',
    origin: 'sweden',
  },
  { name: '55',
    style: 'hi-tech',
    material: 'wool',
    color: 'brown',
    origin: 'sweden',
  },
  { name: '56',
    style: 'hi-tech',
    material: 'leather',
    color: 'brown',
    origin: 'sweden',
  },
  { name: '57',
    style: 'hi-tech',
    material: 'acrylic',
    color: 'white',
    origin: 'sweden',
  },
  { name: '58',
    style: 'hi-tech',
    material: 'polyester',
    color: 'white',
    origin: 'sweden',
  },
  { name: '59',
    style: 'hi-tech',
    material: 'wool',
    color: 'white',
    origin: 'sweden',
  },
  { name: '60',
    style: 'hi-tech',
    material: 'leather',
    color: 'white',
    origin: 'sweden',
  },
  { name: '61',
    style: 'hi-tech',
    material: 'acrylic',
    color: 'red',
    origin: 'sweden',
  },
  { name: '62',
    style: 'hi-tech',
    material: 'polyester',
    color: 'red',
    origin: 'sweden',
  },
  { name: '63',
    style: 'hi-tech',
    material: 'wool',
    color: 'red',
    origin: 'sweden',
  },
  { name: '64',
    style: 'hi-tech',
    material: 'leather',
    color: 'red',
    origin: 'sweden',
  },

  { name: '65',
    style: 'traditional',
    material: 'acrylic',
    color: 'black',
    origin: 'japan',
  },
  { name: '66',
    style: 'traditional',
    material: 'polyester',
    color: 'black',
    origin: 'japan',
  },
  { name: '67',
    style: 'traditional',
    material: 'wool',
    color: 'black',
    origin: 'japan',
  },
  { name: '68',
    style: 'traditional',
    material: 'leather',
    color: 'black',
    origin: 'japan',
  },
  { name: '69',
    style: 'traditional',
    material: 'acrylic',
    color: 'brown',
    origin: 'japan',
  },
  { name: '70',
    style: 'traditional',
    material: 'polyester',
    color: 'brown',
    origin: 'japan',
  },
  { name: '71',
    style: 'traditional',
    material: 'wool',
    color: 'brown',
    origin: 'japan',
  },
  { name: '72',
    style: 'traditional',
    material: 'leather',
    color: 'brown',
    origin: 'japan',
  },
  { name: '73',
    style: 'traditional',
    material: 'acrylic',
    color: 'white',
    origin: 'japan',
  },
  { name: '74',
    style: 'traditional',
    material: 'polyester',
    color: 'white',
    origin: 'japan',
  },
  { name: '75',
    style: 'traditional',
    material: 'wool',
    color: 'white',
    origin: 'japan',
  },
  { name: '76',
    style: 'traditional',
    material: 'leather',
    color: 'white',
    origin: 'japan',
  },
  { name: '77',
    style: 'traditional',
    material: 'acrylic',
    color: 'red',
    origin: 'japan',
  },
  { name: '78',
    style: 'traditional',
    material: 'polyester',
    color: 'red',
    origin: 'japan',
  },
  { name: '79',
    style: 'traditional',
    material: 'wool',
    color: 'red',
    origin: 'japan',
  },
  { name: '80',
    style: 'traditional',
    material: 'leather',
    color: 'red',
    origin: 'japan',
  },

  { name: '81',
    style: 'traditional',
    material: 'acrylic',
    color: 'black',
    origin: 'italy',
  },
  { name: '82',
    style: 'traditional',
    material: 'polyester',
    color: 'black',
    origin: 'italy',
  },
  { name: '83',
    style: 'traditional',
    material: 'wool',
    color: 'black',
    origin: 'italy',
  },
  { name: '84',
    style: 'traditional',
    material: 'leather',
    color: 'black',
    origin: 'italy',
  },
  { name: '85',
    style: 'traditional',
    material: 'acrylic',
    color: 'brown',
    origin: 'italy',
  },
  { name: '86',
    style: 'traditional',
    material: 'polyester',
    color: 'brown',
    origin: 'italy',
  },
  { name: '87',
    style: 'traditional',
    material: 'wool',
    color: 'brown',
    origin: 'italy',
  },
  { name: '88',
    style: 'traditional',
    material: 'leather',
    color: 'brown',
    origin: 'italy',
  },
  { name: '89',
    style: 'traditional',
    material: 'acrylic',
    color: 'white',
    origin: 'italy',
  },
  { name: '90',
    style: 'traditional',
    material: 'polyester',
    color: 'white',
    origin: 'italy',
  },
  { name: '91',
    style: 'traditional',
    material: 'wool',
    color: 'white',
    origin: 'italy',
  },
  { name: '92',
    style: 'traditional',
    material: 'leather',
    color: 'white',
    origin: 'italy',
  },
  { name: '93',
    style: 'traditional',
    material: 'acrylic',
    color: 'red',
    origin: 'italy',
  },
  { name: '94',
    style: 'traditional',
    material: 'polyester',
    color: 'red',
    origin: 'italy',
  },
  { name: '95',
    style: 'traditional',
    material: 'wool',
    color: 'red',
    origin: 'italy',
  },
  { name: '96',
    style: 'traditional',
    material: 'leather',
    color: 'red',
    origin: 'italy',
  },

  { name: '97',
    style: 'traditional',
    material: 'acrylic',
    color: 'black',
    origin: 'sweden',
  },
  { name: '98',
    style: 'traditional',
    material: 'polyester',
    color: 'black',
    origin: 'sweden',
  },
  { name: '99',
    style: 'traditional',
    material: 'wool',
    color: 'black',
    origin: 'sweden',
  },
  { name: '100',
    style: 'traditional',
    material: 'leather',
    color: 'black',
    origin: 'sweden',
  },
  { name: '101',
    style: 'traditional',
    material: 'acrylic',
    color: 'brown',
    origin: 'sweden',
  },
  { name: '102',
    style: 'traditional',
    material: 'polyester',
    color: 'brown',
    origin: 'sweden',
  },
  { name: '103',
    style: 'traditional',
    material: 'wool',
    color: 'brown',
    origin: 'sweden',
  },
  { name: '104',
    style: 'traditional',
    material: 'leather',
    color: 'brown',
    origin: 'sweden',
  },
  { name: '105',
    style: 'traditional',
    material: 'acrylic',
    color: 'white',
    origin: 'sweden',
  },
  { name: '106',
    style: 'traditional',
    material: 'polyester',
    color: 'white',
    origin: 'sweden',
  },
  { name: '107',
    style: 'traditional',
    material: 'wool',
    color: 'white',
    origin: 'sweden',
  },
  { name: '108',
    style: 'traditional',
    material: 'leather',
    color: 'white',
    origin: 'sweden',
  },
  { name: '109',
    style: 'traditional',
    material: 'acrylic',
    color: 'red',
    origin: 'sweden',
  },
  { name: '110',
    style: 'traditional',
    material: 'polyester',
    color: 'red',
    origin: 'sweden',
  },
  { name: '111',
    style: 'traditional',
    material: 'wool',
    color: 'red',
    origin: 'sweden',
  },
  { name: '112',
    style: 'traditional',
    material: 'leather',
    color: 'red',
    origin: 'sweden',
  },

  { name: '113',
    style: 'modern',
    material: 'acrylic',
    color: 'black',
    origin: 'china',
  },
  { name: '114',
    style: 'modern',
    material: 'polyester',
    color: 'black',
    origin: 'china',
  },
  { name: '115',
    style: 'modern',
    material: 'wool',
    color: 'black',
    origin: 'china',
  },
  { name: '116',
    style: 'modern',
    material: 'leather',
    color: 'black',
    origin: 'china',
  },
  { name: '117',
    style: 'modern',
    material: 'acrylic',
    color: 'brown',
    origin: 'china',
  },
  { name: '118',
    style: 'modern',
    material: 'polyester',
    color: 'brown',
    origin: 'china',
  },
  { name: '119',
    style: 'modern',
    material: 'wool',
    color: 'brown',
    origin: 'china',
  },
  { name: '120',
    style: 'modern',
    material: 'leather',
    color: 'brown',
    origin: 'china',
  },
  { name: '121',
    style: 'modern',
    material: 'acrylic',
    color: 'white',
    origin: 'china',
  },
  { name: '122',
    style: 'modern',
    material: 'polyester',
    color: 'white',
    origin: 'china',
  },
  { name: '123',
    style: 'modern',
    material: 'wool',
    color: 'white',
    origin: 'china',
  },
  { name: '124',
    style: 'modern',
    material: 'leather',
    color: 'white',
    origin: 'china',
  },
  { name: '125',
    style: 'modern',
    material: 'acrylic',
    color: 'red',
    origin: 'china',
  },
  { name: '126',
    style: 'modern',
    material: 'polyester',
    color: 'red',
    origin: 'china',
  },
  { name: '127',
    style: 'modern',
    material: 'wool',
    color: 'red',
    origin: 'china',
  },
  { name: '128',
    style: 'modern',
    material: 'leather',
    color: 'red',
    origin: 'china',
  },

  { name: '129',
    style: 'modern',
    material: 'acrylic',
    color: 'black',
    origin: 'japan',
  },
  { name: '130',
    style: 'modern',
    material: 'polyester',
    color: 'black',
    origin: 'japan',
  },
  { name: '131',
    style: 'modern',
    material: 'wool',
    color: 'black',
    origin: 'japan',
  },
  { name: '132',
    style: 'modern',
    material: 'leather',
    color: 'black',
    origin: 'japan',
  },
  { name: '133',
    style: 'modern',
    material: 'acrylic',
    color: 'brown',
    origin: 'japan',
  },
  { name: '134',
    style: 'modern',
    material: 'polyester',
    color: 'brown',
    origin: 'japan',
  },
  { name: '135',
    style: 'modern',
    material: 'wool',
    color: 'brown',
    origin: 'japan',
  },
  { name: '136',
    style: 'modern',
    material: 'leather',
    color: 'brown',
    origin: 'japan',
  },
  { name: '137',
    style: 'modern',
    material: 'acrylic',
    color: 'white',
    origin: 'japan',
  },
  { name: '138',
    style: 'modern',
    material: 'polyester',
    color: 'white',
    origin: 'japan',
  },
  { name: '139',
    style: 'modern',
    material: 'wool',
    color: 'white',
    origin: 'japan',
  },
  { name: '140',
    style: 'modern',
    material: 'leather',
    color: 'white',
    origin: 'japan',
  },
  { name: '141',
    style: 'modern',
    material: 'acrylic',
    color: 'red',
    origin: 'japan',
  },
  { name: '142',
    style: 'modern',
    material: 'polyester',
    color: 'red',
    origin: 'japan',
  },
  { name: '143',
    style: 'modern',
    material: 'wool',
    color: 'red',
    origin: 'japan',
  },
  { name: '144',
    style: 'modern',
    material: 'leather',
    color: 'red',
    origin: 'japan',
  },

  { name: '145',
    style: 'modern',
    material: 'acrylic',
    color: 'black',
    origin: 'italy',
  },
  { name: '146',
    style: 'modern',
    material: 'polyester',
    color: 'black',
    origin: 'italy',
  },
  { name: '147',
    style: 'modern',
    material: 'wool',
    color: 'black',
    origin: 'italy',
  },
  { name: '148',
    style: 'modern',
    material: 'leather',
    color: 'black',
    origin: 'italy',
  },
  { name: '149',
    style: 'modern',
    material: 'acrylic',
    color: 'brown',
    origin: 'italy',
  },
  { name: '150',
    style: 'modern',
    material: 'polyester',
    color: 'brown',
    origin: 'italy',
  },
  { name: '151',
    style: 'modern',
    material: 'wool',
    color: 'brown',
    origin: 'italy',
  },
  { name: '152',
    style: 'modern',
    material: 'leather',
    color: 'brown',
    origin: 'italy',
  },
  { name: '153',
    style: 'modern',
    material: 'acrylic',
    color: 'white',
    origin: 'italy',
  },
  { name: '154',
    style: 'modern',
    material: 'polyester',
    color: 'white',
    origin: 'italy',
  },
  { name: '155',
    style: 'modern',
    material: 'wool',
    color: 'white',
    origin: 'italy',
  },
  { name: '156',
    style: 'modern',
    material: 'leather',
    color: 'white',
    origin: 'italy',
  },
  { name: '157',
    style: 'modern',
    material: 'acrylic',
    color: 'red',
    origin: 'italy',
  },
  { name: '158',
    style: 'modern',
    material: 'polyester',
    color: 'red',
    origin: 'italy',
  },
  { name: '159',
    style: 'modern',
    material: 'wool',
    color: 'red',
    origin: 'italy',
  },
  { name: '160',
    style: 'modern',
    material: 'leather',
    color: 'red',
    origin: 'italy',
  },

  { name: '161',
    style: 'modern',
    material: 'acrylic',
    color: 'black',
    origin: 'sweden',
  },
  { name: '162',
    style: 'modern',
    material: 'polyester',
    color: 'black',
    origin: 'sweden',
  },
  { name: '163',
    style: 'modern',
    material: 'wool',
    color: 'black',
    origin: 'sweden',
  },
  { name: '164',
    style: 'modern',
    material: 'leather',
    color: 'black',
    origin: 'sweden',
  },
  { name: '165',
    style: 'modern',
    material: 'acrylic',
    color: 'brown',
    origin: 'sweden',
  },
  { name: '166',
    style: 'modern',
    material: 'polyester',
    color: 'brown',
    origin: 'sweden',
  },
  { name: '167',
    style: 'modern',
    material: 'wool',
    color: 'brown',
    origin: 'sweden',
  },
  { name: '168',
    style: 'modern',
    material: 'leather',
    color: 'brown',
    origin: 'sweden',
  },
  { name: '169',
    style: 'modern',
    material: 'acrylic',
    color: 'white',
    origin: 'sweden',
  },
  { name: '170',
    style: 'modern',
    material: 'polyester',
    color: 'white',
    origin: 'sweden',
  },
  { name: '171',
    style: 'modern',
    material: 'wool',
    color: 'white',
    origin: 'sweden',
  },
  { name: '172',
    style: 'modern',
    material: 'leather',
    color: 'white',
    origin: 'sweden',
  },
  { name: '173',
    style: 'modern',
    material: 'acrylic',
    color: 'red',
    origin: 'sweden',
  },
  { name: '174',
    style: 'modern',
    material: 'polyester',
    color: 'red',
    origin: 'sweden',
  },
  { name: '175',
    style: 'modern',
    material: 'wool',
    color: 'red',
    origin: 'sweden',
  },
  { name: '176',
    style: 'modern',
    material: 'leather',
    color: 'red',
    origin: 'sweden',
  },

  { name: '177',
    style: 'modern',
    material: 'acrylic',
    color: 'black',
    origin: 'china',
  },
  { name: '178',
    style: 'modern',
    material: 'polyester',
    color: 'black',
    origin: 'china',
  },
  { name: '179',
    style: 'modern',
    material: 'wool',
    color: 'black',
    origin: 'china',
  },
  { name: '180',
    style: 'modern',
    material: 'leather',
    color: 'black',
    origin: 'china',
  },
  { name: '181',
    style: 'modern',
    material: 'acrylic',
    color: 'brown',
    origin: 'china',
  },
  { name: '182',
    style: 'modern',
    material: 'polyester',
    color: 'brown',
    origin: 'china',
  },
  { name: '183',
    style: 'modern',
    material: 'wool',
    color: 'brown',
    origin: 'china',
  },
  { name: '184',
    style: 'modern',
    material: 'leather',
    color: 'brown',
    origin: 'china',
  },
  { name: '185',
    style: 'modern',
    material: 'acrylic',
    color: 'white',
    origin: 'china',
  },
  { name: '186',
    style: 'modern',
    material: 'polyester',
    color: 'white',
    origin: 'china',
  },
  { name: '187',
    style: 'modern',
    material: 'wool',
    color: 'white',
    origin: 'china',
  },
  { name: '188',
    style: 'modern',
    material: 'leather',
    color: 'white',
    origin: 'china',
  },
  { name: '189',
    style: 'modern',
    material: 'acrylic',
    color: 'red',
    origin: 'china',
  },
  { name: '190',
    style: 'modern',
    material: 'polyester',
    color: 'red',
    origin: 'china',
  },
  { name: '191',
    style: 'modern',
    material: 'wool',
    color: 'red',
    origin: 'china',
  },
  { name: '192',
    style: 'modern',
    material: 'leather',
    color: 'red',
    origin: 'china',
  },

  { name: '193',
    style: 'art-deco',
    material: 'acrylic',
    color: 'black',
    origin: 'japan',
  },
  { name: '194',
    style: 'art-deco',
    material: 'polyester',
    color: 'black',
    origin: 'japan',
  },
  { name: '195',
    style: 'art-deco',
    material: 'wool',
    color: 'black',
    origin: 'japan',
  },
  { name: '196',
    style: 'art-deco',
    material: 'leather',
    color: 'black',
    origin: 'japan',
  },
  { name: '197',
    style: 'art-deco',
    material: 'acrylic',
    color: 'brown',
    origin: 'japan',
  },
  { name: '198',
    style: 'art-deco',
    material: 'polyester',
    color: 'brown',
    origin: 'japan',
  },
  { name: '199',
    style: 'art-deco',
    material: 'wool',
    color: 'brown',
    origin: 'japan',
  },
  { name: '200',
    style: 'art-deco',
    material: 'leather',
    color: 'brown',
    origin: 'japan',
  },
  { name: '201',
    style: 'art-deco',
    material: 'acrylic',
    color: 'white',
    origin: 'japan',
  },
  { name: '202',
    style: 'art-deco',
    material: 'polyester',
    color: 'white',
    origin: 'japan',
  },
  { name: '203',
    style: 'art-deco',
    material: 'wool',
    color: 'white',
    origin: 'japan',
  },
  { name: '204',
    style: 'art-deco',
    material: 'leather',
    color: 'white',
    origin: 'japan',
  },
  { name: '205',
    style: 'art-deco',
    material: 'acrylic',
    color: 'red',
    origin: 'japan',
  },
  { name: '206',
    style: 'art-deco',
    material: 'polyester',
    color: 'red',
    origin: 'japan',
  },
  { name: '207',
    style: 'art-deco',
    material: 'wool',
    color: 'red',
    origin: 'japan',
  },
  { name: '208',
    style: 'art-deco',
    material: 'leather',
    color: 'red',
    origin: 'japan',
  },

  { name: '209',
    style: 'art-deco',
    material: 'acrylic',
    color: 'black',
    origin: 'italy',
  },
  { name: '210',
    style: 'art-deco',
    material: 'polyester',
    color: 'black',
    origin: 'italy',
  },
  { name: '211',
    style: 'art-deco',
    material: 'wool',
    color: 'black',
    origin: 'italy',
  },
  { name: '212',
    style: 'art-deco',
    material: 'leather',
    color: 'black',
    origin: 'italy',
  },
  { name: '213',
    style: 'art-deco',
    material: 'acrylic',
    color: 'brown',
    origin: 'italy',
  },
  { name: '214',
    style: 'art-deco',
    material: 'polyester',
    color: 'brown',
    origin: 'italy',
  },
  { name: '215',
    style: 'art-deco',
    material: 'wool',
    color: 'brown',
    origin: 'italy',
  },
  { name: '216',
    style: 'art-deco',
    material: 'leather',
    color: 'brown',
    origin: 'italy',
  },
  { name: '217',
    style: 'art-deco',
    material: 'acrylic',
    color: 'white',
    origin: 'italy',
  },
  { name: '218',
    style: 'art-deco',
    material: 'polyester',
    color: 'white',
    origin: 'italy',
  },
  { name: '219',
    style: 'art-deco',
    material: 'wool',
    color: 'white',
    origin: 'italy',
  },
  { name: '220',
    style: 'art-deco',
    material: 'leather',
    color: 'white',
    origin: 'italy',
  },
  { name: '221',
    style: 'art-deco',
    material: 'acrylic',
    color: 'red',
    origin: 'italy',
  },
  { name: '222',
    style: 'art-deco',
    material: 'polyester',
    color: 'red',
    origin: 'italy',
  },
  { name: '223',
    style: 'art-deco',
    material: 'wool',
    color: 'red',
    origin: 'italy',
  },
  { name: '224',
    style: 'art-deco',
    material: 'leather',
    color: 'red',
    origin: 'italy',
  },

  { name: '225',
    style: 'art-deco',
    material: 'acrylic',
    color: 'black',
    origin: 'sweden',
  },
  { name: '226',
    style: 'art-deco',
    material: 'polyester',
    color: 'black',
    origin: 'sweden',
  },
  { name: '227',
    style: 'art-deco',
    material: 'wool',
    color: 'black',
    origin: 'sweden',
  },
  { name: '228',
    style: 'art-deco',
    material: 'leather',
    color: 'black',
    origin: 'sweden',
  },
  { name: '229',
    style: 'art-deco',
    material: 'acrylic',
    color: 'brown',
    origin: 'sweden',
  },
  { name: '230',
    style: 'art-deco',
    material: 'polyester',
    color: 'brown',
    origin: 'sweden',
  },
  { name: '231',
    style: 'art-deco',
    material: 'wool',
    color: 'brown',
    origin: 'sweden',
  },
  { name: '232',
    style: 'art-deco',
    material: 'leather',
    color: 'brown',
    origin: 'sweden',
  },
  { name: '233',
    style: 'art-deco',
    material: 'acrylic',
    color: 'white',
    origin: 'sweden',
  },
  { name: '234',
    style: 'art-deco',
    material: 'polyester',
    color: 'white',
    origin: 'sweden',
  },
  { name: '235',
    style: 'art-deco',
    material: 'wool',
    color: 'white',
    origin: 'sweden',
  },
  { name: '236',
    style: 'art-deco',
    material: 'leather',
    color: 'white',
    origin: 'sweden',
  },
  { name: '237',
    style: 'art-deco',
    material: 'acrylic',
    color: 'red',
    origin: 'sweden',
  },
  { name: '238',
    style: 'art-deco',
    material: 'polyester',
    color: 'red',
    origin: 'sweden',
  },
  { name: '239',
    style: 'art-deco',
    material: 'wool',
    color: 'red',
    origin: 'sweden',
  },
  { name: '240',
    style: 'art-deco',
    material: 'leather',
    color: 'red',
    origin: 'sweden',
  },
];
